#!/usr/bin/env bash
# This script installs nginx on the server and configures it

# Update the package lists for upgrades and new package installations
apt-get update -y

# Install nginx
apt-get install nginx -y

# Start nginx
service nginx start

# Create a custom HTML file
echo "Hello World!" > /var/www/html/index.html

# Modify the default Nginx configuration file to use the custom HTML file
sed -i 's|root /var/www/html;|root /var/www/html/index.html;|' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
