#!/usr/bin/env bash
# This script creates an answer file for multiple choice questions

# Write the answers to the file
echo "2" > 0-OSI_model
echo "2" >> 0-OSI_model

# Display the content of the file
cat 0-OSI_model
