#!/usr/bin/env bash
# This script answers multiple choice questions about networking

# Write the answers to the file
echo "3" > network_answers
echo "2" >> network_answers
echo "1" >> network_answers

# Display the content of the file
cat network_answers
