#!/usr/bin/env bash
# This script installs and configures Nginx to listen on port 80
apt-get update -y && apt-get install -y nginx
service nginx stop
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
service nginx start

