#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd in a specific format

while IFS=: read -r username password userid groupid _ homedir shell
do
   echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userid"
done < /etc/passwd
