#!/usr/bin/env bash
# This script loops from 1 to 20 and displays different messages based on the iteration number

counter=1
while [ $counter -le 20 ]
do
   echo $counter
   case $counter in
   4)
      echo "bad luck from China"
      ;;
   9)
      echo "bad luck from Japan"
      ;;
   17)
      echo "bad luck from Italy"
      ;;
   esac
   ((counter++))
done
