#!/usr/bin/env bash
# Update /etc/hosts to set localhost to 127.0.0.2
sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts

# Update /etc/hosts to set facebook.com to 8.8.8.8
sudo sed -i 's/157.240.11.35 facebook.com/8.8.8.8 facebook.com/' /etc/hosts
